-- CreateTable
CREATE TABLE `TestRun` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `executedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `status` VARCHAR(191) NOT NULL,
    `bugCount` INTEGER NOT NULL DEFAULT 0,
    `coverage` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
